name: Docker Build

on:
  push:
    tags:
      - 'v*.*.*'  # Esto asegura que solo se dispare cuando el push es de un tag como v1.0.0, v1.2.3, etc.

env:
  IMAGE_NAME: jmmartinezr/test-tema-12
  DOCKERFILE_PATH: Dockerfile
  # Aquí estamos obteniendo el SHA del commit que es parte del evento de push
  SHA: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del código
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ env.SHA }}  # Checkout del código para el commit específico del tag

      # Paso 2: Configuración de Docker Buildx
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Paso 3: Login en Docker Hub
      - name: Log into Docker Hub
        uses: docker/login-action@v2
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}  # Asegúrate de configurar este secreto
          password: ${{ secrets.DOCKER_PASSWORD }}  # Asegúrate de configurar este secreto

      # Paso 4: Construir la imagen Docker
      - name: Build Docker image
        run: |
          docker build -f ${{ env.DOCKERFILE_PATH }} -t ${{ env.IMAGE_NAME }}:${{ github.sha }} .

      # Paso 5: Subir la imagen a Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ env.IMAGE_NAME }}:${{ github.sha }}
