name: docker-build

on:
  push:
    tags: ["v*.*.*"]


env:
  IMAGE_NAME: jmmartinezr29/test-tema-12
  SHA: ${{ github.sha }}
  DOCKERFILE_PATH: Dockerfile

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ env.SHA }}

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into registry
        uses: docker/login-action@v2
        with: 
          username: jmmartinezr
          password: ${{ secrets.MI_PTA_DOCKERHUB }}