name: docker-build

on:
  push:
    tags:
      - 'v*.*.*'  # Solo se ejecuta para tags con el formato v1.0.0, v1.2.3, etc.

env:
  IMAGE_NAME: jmmartinezr/test-tema-12
  SHA: ${{ github.sha }}  # Usamos github.sha para el SHA del commit del push
  DOCKERFILE_PATH: Dockerfile

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ env.SHA }}  # Checkout usando el SHA del commit del push

      # Paso 2: Configurar Docker Buildx
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      # Paso 3: Login en Docker Hub
      - name: Log into Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Asegúrate de que este secreto esté configurado
          password: ${{ secrets.MI_PTA_DOCKERHUB }}  # Secreto con tu contraseña o token de Docker Hub

      # Paso 4: Construir la imagen Docker
      - name: Build Docker image
        run: |
          docker build -f ${{ env.DOCKERFILE_PATH }} -t ${{ env.IMAGE_NAME }}:${{ env.SHA }} .

      # Paso 5: Subir la imagen Docker
      - name: Push Docker image
        run: |
          docker push ${{ env.IMAGE_NAME }}:${{ env.SHA }}
